apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: platform
  name: equal-experts-sample-role-binding
subjects:
  - kind: ServiceAccount
    name: equal-experts-sample-sa
    namespace: platform
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: equal-experts-sample-role
  apiGroup: rbac.authorization.k8s.io