apiVersion: v1
kind: Service
metadata:
  name: equal-experts-sample
  namespace: platform
  labels:
    app : equal-experts-sample
    team: platform-team
    name: equal-experts-sample
spec:
  type: NodePort
  selector:
    app : equal-experts-sample
    team: platform-team
    name: equal-experts-sample
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30133
      name: equal-experts