apiVersion: v1
kind: ServiceAccount
metadata:
  name: equal-experts-sample-sa
  namespace: platform
  labels:
    app : equal-experts-sample
    team: platform-team
    name: equal-experts-sample
